--- #YAML:1.0
name:               CGI-RSS
version:            0.95
abstract:           ~
author:  []
license:            lgpl2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Deparse:   0
    Date::Manip:  0
    perl:         5.008
resources:
    repository:  http://github.com/jettero/cgi--rss/tree
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - cgi
    - rss
