---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords:
  - cgi
  - rss
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-RSS
no_index:
  directory:
    - t
    - inc
requires:
  B::Deparse: 0
  Date::Manip: 0
  perl: 5.008
resources:
  repository: http://github.com/jettero/cgi--rss/tree
version: 0.9655
